### ISSUE TITLE
Toggleable Music for every game like it is in Island Utils

### ISSUE THREAD

**Issue by kispintyi** [dvitski/companion#26]
I think this would be a great idea for those that do not want to listen to a game's music or for those that want to use the TGTTOS double time music from Island Utils without playing 2 songs at once (one sped up)
(ooooooor for me to listen to the 2 Remix without playing 2 different songs at the same time :))
Like this (Toggleable game music settings): ![2023-06-16_14 06 51](https://github.com/andantet/companion/assets/116653691/9405a25f-1dcd-49a4-94f9-694e47b9a9f7)

**Comment by dvitski** [comment]
Added in de88377c4463f0ea1374e32a93817a7172668147
