### ISSUE TITLE
Music is bugged again in mcc island

### ISSUE THREAD

**Issue by OmegaPhoenix637** [dvitski/companion#28]
Music is not stopping when it should

**Comment by dvitski** [comment]
Could you provide an example of when this occurs?

**Comment by kispintyi** [comment]
For me the Music in Battle Box does not stop and after some minute it stops and doesn't start again

**Comment by dvitski** [comment]
I've identified the problem, and I'll be implementing a more long-term fix for the next alpha.

**Comment by OmegaPhoenix637** [comment]
The music works fine in games where the music doesn't need to stop, like pkw and sb and hitw, only not when you die or the game ends. And in bb and tgttos the music doesn't stop or start of the end of a round, or when you are done.

**Comment by dvitski** [comment]
The mod detects when a message in chat says 'Round over!' Unfortunately, this broke as Noxcrew changed the texts to say 'Round Over!'. That capitalisation difference breaks the detection
