### ISSUE TITLE
4.0 Doesn't Do Anything?

### ISSUE THREAD

**Issue by JTModel3** [dvitski/companion#31]
Howdy, I was just playing around with Companion and it doesn't seem to be doing any of the pop-ups or anything. I understand 5.0 doesn't have any of these features yet, but why isn't 4.0 working?

**Comment by dvitski** [comment]
MCC Island has recently updated and changed a few of the things that MCCIC uses to detect certain features.

I'll get these updated soon and send a comment here when that's done!

**Comment by dvitski** [comment]
Should be fixed now, let me know if you still experience any issues :)
