### ISSUE TITLE
Crash, when you want to turn off Music

### ISSUE THREAD

**Issue by Kubertinos** [dvitski/companion#5]
Hi.
I recently downloaded this mod and it is working fine, but when i try to turn off the music by command /mccis config open music, it immediately crashes and can´t turn it of. Is there any fix for this?
Thanks.

**Comment by dvitski** [comment]
Could you send a crash report?

**Comment by Kubertinos** [comment]
1. When it crashes, it doesn´t show crash log in Minecraft launcher (basically, it doesn´t open at all
2. I can´t find it in logs, i searched in latest.log, debug.log and even in todays date.zip, but couldn´t find anything

**Comment by dvitski** [comment]
Hmm this sounds bizarre, there's not much I can do

Does the same thing happen if you use Mod Menu and go into the config from there?

**Comment by Kubertinos** [comment]
If I use it from mod menu, i got message like this, idk, if i did something bad, coz i use Fabric for first time ever.
![image](https://user-images.githubusercontent.com/117541179/200160503-dc245fdd-9404-4203-a6c5-3831a0e86185.png)

**Comment by dvitski** [comment]
That's the base config menu, entirely normal

Here's the music config menu:
![image](https://user-images.githubusercontent.com/36608902/200176400-e26cbb51-cb9b-484b-900e-63b5de84d297.png)

**Comment by dvitski** [comment]
Any updates?

**Comment by Kubertinos** [comment]
Hi. Sorry for no responding, i didnt have time to check my email. I will
try to reinstall the plugin and let you know.

**Comment by dvitski** [comment]
Alrighty!
